export enum VogStyle {
    BASIC = 'BASIC',
    BOHEM = 'BOHEM',
    BUSINESS_CASUAL = 'BUSINESS_CASUAL',
    CASUAL = 'CASUAL',
    OUTDOOR = 'OUTDOOR',
    RETRO = 'RETRO',
    SPORTLUXE = 'SPORTLUXE',
    STREET_STYLE = 'STREET_STYLE',
    ABIYE = 'ABIYE',
    BUSINESS = 'BUSINESS',
    MINIMALIST = 'MINIMALIST',
    SMART_CASUAL = 'SMART_CASUAL',
    SPORTLIFE = 'SPORTLIFE',
    TESETTUR = 'TESETTUR',
    VINTAGE = 'VINTAGE',
    ELEGANT = 'ELEGANT',
    GRUNGE = 'GRUNGE',
    PREPPY = 'PREPPY',
    PUNK = 'PUNK',
    GOTHIC = 'GOTHIC',
    HIPSTER = 'HIPSTER',
    TECHWEAR = 'TECHWEAR',
    ATHLEISURE = 'ATHLEISURE',
    MATERNITY = 'MATERNITY',
    ROCK_CHIC = 'ROCK_CHIC',
    MASCULINE = 'MASCULINE',
    ANDROJEN = 'ANDROJEN',
    GLAM = 'GLAM',
    SPORT_GLAM = 'SPORT_GLAM',
    COZY_HOMEWEAR = 'COZY_HOMEWEAR',
    HARAJUKU = 'HARAJUKU',
    MILITARY = 'MILITARY',
    ETHNIC = 'ETHNIC',
    AVANTGARDE = 'AVANTGARDE',
    OLD_MONEY_STYLE = 'OLD_MONEY_STYLE',
    AUTHENTIC = 'AUTHENTIC',
    KOREAN_STYLE = 'KOREAN_STYLE',
    Y2K = 'Y2K',
    ASIAN = 'ASIAN',
    AFRICAN = 'AFRICAN',
    MONOKROM = 'MONOKROM',
    LAYERING = 'LAYERING',
    ECOLOGICAL_STYLE = 'ECOLOGICAL_STYLE',
    MIDDLE_EASTERN_STYLE = 'MIDDLE_EASTERN_STYLE',
    DENIM_ON_DENIM = 'DENIM_ON_DENIM',
    NORMCORE = 'NORMCORE',
    SAFARI = 'SAFARI',
    ROMANTIC = 'ROMANTIC',
  }
  
  export const VogStyleLabels = {
    [VogStyle.BASIC]: "Basic",
    [VogStyle.BOHEM]: "Bohem",
    [VogStyle.BUSINESS_CASUAL]: "Business Casual",
    [VogStyle.CASUAL]: "Casual",
    [VogStyle.OUTDOOR]: "Outdoor",
    [VogStyle.RETRO]: "Retro",
    [VogStyle.SPORTLUXE]: "Sportluxe",
    [VogStyle.STREET_STYLE]: "Street Style",
    [VogStyle.ABIYE]: "Abiye",
    [VogStyle.BUSINESS]: "Business",
    [VogStyle.MINIMALIST]: "Minimalist",
    [VogStyle.SMART_CASUAL]: "Smart Casual",
    [VogStyle.SPORTLIFE]: "Sportlife",
    [VogStyle.TESETTUR]: "Tesettür",
    [VogStyle.VINTAGE]: "Vintage",
    [VogStyle.ELEGANT]: "Elegant",
    [VogStyle.GRUNGE]: "Grunge",
    [VogStyle.PREPPY]: "Preppy",
    [VogStyle.PUNK]: "Punk",
    [VogStyle.GOTHIC]: "Gothic",
    [VogStyle.HIPSTER]: "Hipster",
    [VogStyle.TECHWEAR]: "Techwear",
    [VogStyle.ATHLEISURE]: "Athleisure",
    [VogStyle.MATERNITY]: "Maternity",
    [VogStyle.ROCK_CHIC]: "Rock Chic",
    [VogStyle.MASCULINE]: "Masculine",
    [VogStyle.ANDROJEN]: "Androjen",
    [VogStyle.GLAM]: "Glam",
    [VogStyle.SPORT_GLAM]: "Sport Glam",
    [VogStyle.COZY_HOMEWEAR]: "Cozy Homewear",
    [VogStyle.HARAJUKU]: "Harajuku",
    [VogStyle.MILITARY]: "Military",
    [VogStyle.ETHNIC]: "Ethnic",
    [VogStyle.AVANTGARDE]: "Avantgarde",
    [VogStyle.OLD_MONEY_STYLE]: "Old Money Style",
    [VogStyle.AUTHENTIC]: "Authentic",
    [VogStyle.KOREAN_STYLE]: "Korean Style",
    [VogStyle.Y2K]: "Y2K",
    [VogStyle.ASIAN]: "Asian",
    [VogStyle.AFRICAN]: "African",
    [VogStyle.MONOKROM]: "Monokrom",
    [VogStyle.LAYERING]: "Layering",
    [VogStyle.ECOLOGICAL_STYLE]: "Ecological Style",
    [VogStyle.MIDDLE_EASTERN_STYLE]: "Middle Eastern Style",
    [VogStyle.DENIM_ON_DENIM]: "Denim on Denim",
    [VogStyle.NORMCORE]: "Normcore",
    [VogStyle.SAFARI]: "Safari",
    [VogStyle.ROMANTIC]: "Romantic",
  };
  
  export const VogStyleOptions = () => {
    return Object.values(VogStyle).map((style) => ({
      label: VogStyleLabels[style],
      value: style,
    }));
  };
  
  export const getVogStyleOption = (value: VogStyle) => {
    return VogStyleOptions().find((option) => option.value === value);
  };