import { ISingleResourceRoute } from "../../types/IRoutes";

export const USER_ROUTES: ISingleResourceRoute = {
  GET: {
    ALL_WITH_PAGINATION: "user/find/all",
    BY_AUTH_ID: "user/find/byAuthId",
  },
  CREATE: {},
  UPDATE: {
    about: "-1",
    accountStatus: "-1",
    accountType: "-1",
    accountVerifiedDate: "-1",
    authId: "-1",
    authType: "-1",
    avatarUrl: "-1",
    banDate: "-1",
    birthDate: "-1",
    blogsLikeCount: "-1",
    blogsReadCount: "-1",
    businessViewCount: "-1",
    chatCount: "-1",
    city: "-1",
    coefficient: "-1",
    country: "-1",
    createDate: "-1",
    deleteDate: "-1",
    emailAddress: "-1",
    expireBanDate: "-1",
    favoriteBusinessCount: "-1",
    followerCount: "-1",
    followingCount: "-1",
    frozenDate: "-1",
    isAccountVerified: "-1",
    isBanned: "-1",
    isDeleted: "-1",
    isEmailVerified: "-1",
    isFrozen: "-1",
    isPhoneVerified: "-1",
    lastIpAddress: "-1",
    lastLoginDate: "-1",
    lastLogoutDate: "-1",
    notificationCount: "-1",
    notificationIds: "-1",
    numberId: "-1",
    password: "-1",
    phoneNumber: "-1",
    postCommentCount: "-1",
    premiumVogCount: "-1",
    questionCommentCount: "-1",
    questionCount: "-1",
    realname: "-1",
    sex: "-1",
    socialAccounts: "-1",
    subscriberCount: "-1",
    subscriptionCount: "-1",
    topicList: "-1",
    totalExpenditure: "-1",
    userStatus: "-1",
    userType: "-1",
    username: "-1",
    usernameChangedDate: "-1",
    vogCount: "-1",
    vogLikeCount: "-1",
  },
  DELETE: {
    BY_AUTH_ID: "user/find/byAuthId",
  },
};
